name: lab04_frontend
description: A Flutter lab for database and persistence operations

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Database and storage
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # JSON serialization
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # JSON code generation
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  
  # Testing dependencies
  sqflite_common_ffi: ^2.3.0
  
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
