name: lab05_frontend
description: Lab 05 - Advanced Patterns Flutter Project
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core dependencies for clean architecture
  equatable: ^2.0.5
  dartz: ^0.10.1
  
  # Secure storage for tokens
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true 