// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/calculator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for basic operations
type OperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             float64                `protobuf:"fixed64,1,opt,name=a,proto3" json:"a,omitempty"`
	B             float64                `protobuf:"fixed64,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationRequest) Reset() {
	*x = OperationRequest{}
	mi := &file_proto_calculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationRequest) ProtoMessage() {}

func (x *OperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationRequest.ProtoReflect.Descriptor instead.
func (*OperationRequest) Descriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *OperationRequest) GetA() float64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *OperationRequest) GetB() float64 {
	if x != nil {
		return x.B
	}
	return 0
}

// Response message for operations
type OperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        float64                `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationResponse) Reset() {
	*x = OperationResponse{}
	mi := &file_proto_calculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResponse) ProtoMessage() {}

func (x *OperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResponse.ProtoReflect.Descriptor instead.
func (*OperationResponse) Descriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *OperationResponse) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *OperationResponse) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *OperationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OperationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Request for operation history
type HistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryRequest) Reset() {
	*x = HistoryRequest{}
	mi := &file_proto_calculator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRequest) ProtoMessage() {}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRequest.ProtoReflect.Descriptor instead.
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{2}
}

func (x *HistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Response with operation history
type HistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*HistoryEntry        `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_proto_calculator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{3}
}

func (x *HistoryResponse) GetEntries() []*HistoryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// Individual history entry
type HistoryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     string                 `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	A             float64                `protobuf:"fixed64,2,opt,name=a,proto3" json:"a,omitempty"`
	B             float64                `protobuf:"fixed64,3,opt,name=b,proto3" json:"b,omitempty"`
	Result        float64                `protobuf:"fixed64,4,opt,name=result,proto3" json:"result,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryEntry) Reset() {
	*x = HistoryEntry{}
	mi := &file_proto_calculator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryEntry) ProtoMessage() {}

func (x *HistoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryEntry.ProtoReflect.Descriptor instead.
func (*HistoryEntry) Descriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{4}
}

func (x *HistoryEntry) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *HistoryEntry) GetA() float64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *HistoryEntry) GetB() float64 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *HistoryEntry) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *HistoryEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_calculator_proto protoreflect.FileDescriptor

const file_proto_calculator_proto_rawDesc = "" +
	"\n" +
	"\x16proto/calculator.proto\x12\n" +
	"calculator\".\n" +
	"\x10OperationRequest\x12\f\n" +
	"\x01a\x18\x01 \x01(\x01R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x01R\x01b\"y\n" +
	"\x11OperationResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x01R\x06result\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"&\n" +
	"\x0eHistoryRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"E\n" +
	"\x0fHistoryResponse\x122\n" +
	"\aentries\x18\x01 \x03(\v2\x18.calculator.HistoryEntryR\aentries\"~\n" +
	"\fHistoryEntry\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\tR\toperation\x12\f\n" +
	"\x01a\x18\x02 \x01(\x01R\x01a\x12\f\n" +
	"\x01b\x18\x03 \x01(\x01R\x01b\x12\x16\n" +
	"\x06result\x18\x04 \x01(\x01R\x06result\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp2\xf0\x02\n" +
	"\n" +
	"Calculator\x12B\n" +
	"\x03Add\x12\x1c.calculator.OperationRequest\x1a\x1d.calculator.OperationResponse\x12G\n" +
	"\bSubtract\x12\x1c.calculator.OperationRequest\x1a\x1d.calculator.OperationResponse\x12G\n" +
	"\bMultiply\x12\x1c.calculator.OperationRequest\x1a\x1d.calculator.OperationResponse\x12E\n" +
	"\x06Divide\x12\x1c.calculator.OperationRequest\x1a\x1d.calculator.OperationResponse\x12E\n" +
	"\n" +
	"GetHistory\x12\x1a.calculator.HistoryRequest\x1a\x1b.calculator.HistoryResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_calculator_proto_rawDescOnce sync.Once
	file_proto_calculator_proto_rawDescData []byte
)

func file_proto_calculator_proto_rawDescGZIP() []byte {
	file_proto_calculator_proto_rawDescOnce.Do(func() {
		file_proto_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_calculator_proto_rawDesc), len(file_proto_calculator_proto_rawDesc)))
	})
	return file_proto_calculator_proto_rawDescData
}

var file_proto_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_calculator_proto_goTypes = []any{
	(*OperationRequest)(nil),  // 0: calculator.OperationRequest
	(*OperationResponse)(nil), // 1: calculator.OperationResponse
	(*HistoryRequest)(nil),    // 2: calculator.HistoryRequest
	(*HistoryResponse)(nil),   // 3: calculator.HistoryResponse
	(*HistoryEntry)(nil),      // 4: calculator.HistoryEntry
}
var file_proto_calculator_proto_depIdxs = []int32{
	4, // 0: calculator.HistoryResponse.entries:type_name -> calculator.HistoryEntry
	0, // 1: calculator.Calculator.Add:input_type -> calculator.OperationRequest
	0, // 2: calculator.Calculator.Subtract:input_type -> calculator.OperationRequest
	0, // 3: calculator.Calculator.Multiply:input_type -> calculator.OperationRequest
	0, // 4: calculator.Calculator.Divide:input_type -> calculator.OperationRequest
	2, // 5: calculator.Calculator.GetHistory:input_type -> calculator.HistoryRequest
	1, // 6: calculator.Calculator.Add:output_type -> calculator.OperationResponse
	1, // 7: calculator.Calculator.Subtract:output_type -> calculator.OperationResponse
	1, // 8: calculator.Calculator.Multiply:output_type -> calculator.OperationResponse
	1, // 9: calculator.Calculator.Divide:output_type -> calculator.OperationResponse
	3, // 10: calculator.Calculator.GetHistory:output_type -> calculator.HistoryResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_calculator_proto_init() }
func file_proto_calculator_proto_init() {
	if File_proto_calculator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_calculator_proto_rawDesc), len(file_proto_calculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_calculator_proto_goTypes,
		DependencyIndexes: file_proto_calculator_proto_depIdxs,
		MessageInfos:      file_proto_calculator_proto_msgTypes,
	}.Build()
	File_proto_calculator_proto = out.File
	file_proto_calculator_proto_goTypes = nil
	file_proto_calculator_proto_depIdxs = nil
}
